### ISSUE TITLE
Front Camera not working

### ISSUE THREAD

**Issue by duxa174** [LegacyHuawei/local_manifests#4]
Stock Camera app doesn't switch on the front camera. I get the error "Camera error. Can't connect to the camera".
Build: u8860 cm-11-20150815

**Comment by rtammekivi** [comment]
Logs? Install SysLog app, try to use front camera and take logs afterwards with SysLog

**Comment by duxa174** [comment]
[Logs](https://www.dropbox.com/s/yodgajd22hqxc1k/2015-08-21_19.25.zip?dl=1)

**Comment by rtammekivi** [comment]
Ok, seems like a fix was not merged to CM11.
Fix located in cm-12.1 here: https://github.com/LegacyHuawei/android_device_huawei_msm7x30-common/commit/e855410a55f26c6084b1487a1b282438f51ada86

If you're ok with it, I will compile a newer mediaserver library with the patch, so you could have it working?

**Comment by duxa174** [comment]
I have compiled an android ROM from source with this commit. Front camera is working now. Thanks)

**Comment by rtammekivi** [comment]
Good to know :). Next cm-11.0 build will have it fixed.
